#cloud-config
packages:
  - git

runcmd:
  - rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
  - yum -y install puppet-agent
  - /opt/puppetlabs/puppet/bin/gem install r10k -v 2.6.4
  - git clone https://git.computecanada.ca/fafor10/slurm_cloud_puppet.git /root/puppet
  - /opt/puppetlabs/puppet/bin/r10k puppetfile install --moduledir /root/puppet/modules --puppetfile=/root/puppet/Puppetfile
  - /opt/puppetlabs/bin/puppet apply --modulepath=/root/puppet/modules:/root/puppet/site /root/puppet/site.pp --color=false --logdest /var/log/puppetlabs/puppet/puppet.log
  - "echo '@reboot /opt/puppetlabs/bin/puppet apply --modulepath=/root/puppet/modules:/root/puppet/site /root/puppet/site.pp --color=false --logdest /var/log/puppetlabs/puppet/puppet.log' | crontab -"
  - reboot -n

write_files:
  - content: |
      ---
      version: 5
      defaults:
        datadir: /etc/puppetlabs/puppet/hieradata
        data_hash: yaml_data
      hierarchy:
        - name: "Other YAML hierarchy levels"
          paths:
            - "common.yaml"
    path: /etc/puppetlabs/puppet/hiera.yaml
  - content: |
      ---
      profile::freeipa::base::admin_passwd: "${admin_passwd}"
      profile::freeipa::base::domain_name: "${domain_name}"
      profile::freeipa::base::dns_ip: "${dns_ip}"
      profile::freeipa::guest_accounts::guest_passwd: "${guest_passwd}"
      profile::freeipa::guest_accounts::nb_accounts: ${nb_users}
      profile::slurm::base::cluster_name: "${cluster_name}"
      profile::slurm::base::munge_key: "${munge_key}"
      jupyterhub::domain_name: "${domain_name}"
    path: /etc/puppetlabs/puppet/hieradata/common.yaml
    owner: root:root
    permissions: "0600"

disable_ec2_metadata: false
timezone: "America/Montreal"
output: { all: "| tee -a /var/log/cloud-init-output.log" }
